### ISSUE TITLE
Integation of a Highlight code editor for Html, CSS and javascript

### ISSUE THREAD

**Issue by Sanix-Darker** [Sanix-Darker/Weby#1]
Just for look like Sublime Text or another code editor

**Comment by MKRhere** [comment]
Use something like this:
https://highlightjs.org/

**Comment by Sanix-Darker** [comment]
Looks great, thank's @MKRhere !!

**Comment by MKRhere** [comment]
Looks like `<textarea>` has a limitation. You cannot have full control over its contents, hence cannot really highlight code within `<textarea`>.
Should move to a JS based editor: https://ace.c9.io/

**Comment by Sanix-Darker** [comment]
okk @MKRhere  I will check it!!!

**Comment by Wh1teShad0w** [comment]
mmmmhh i don't think is necessary @MKRhere !!!
