### ISSUE TITLE
Integrate many frame for learning to code[HTML, CSS] or [Javascript], when changing options

### ISSUE THREAD

**Issue by Sanix-Darker** [Sanix-Darker/Weby#2]
When a user clic on the option select, and select learn Html or css, or on learn javascript, on the right of output, the appear accordion with frames of differents tutorials(good for beginner as well)
[PS: Sorry if i make some english mistake, am a french speaker ]

**Comment by Wh1teShad0w** [comment]
Oh, nice, to integrate the learning in the project!!! NICE @Sanix-Darker !!!
